<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Google.Apis.Calendar.v3" Version="1.40.2.1611" />
    <PackageReference Include="Microsoft.Bcl.Async" Version="1.0.168" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="2.2.6" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="2.2.6" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="2.2.6" />
    <PackageReference Include="Microsoft.IdentityModel.Tokens" Version="5.5.0" />
    <PackageReference Include="Sendgrid" Version="9.11.0" />
    <PackageReference Include="System.Threading.Tasks" Version="4.3.0" />
  </ItemGroup>
  
</Project>
